version: '3'

services:
  app-yeahyeahyeah:
    image: 'ghcr.io/smartive-education/app-yeahyeahyeah:latest'
    container_name: app-yeahyeahyeah
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app-yeahyeahyeah
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email thomas.schallert@gmail.com --agree-tos --no-eff-email --staging -d mumble-yeahyeahyeah.ch  -d www.mumble-yeahyeahyeah.ch

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/thomas.schallert@fhnw.ch/Projects/app-yeahyeahyeah/views
      o: bind

networks:
  app-network:
    driver: bridge
