name: Build and deploy app-yeahyeahyeah

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  autenticate:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'

      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://europe-west6-docker.pkg.dev
