name: Build and deploy app-yeahyeahyeah

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy app-yeahyeahyeah
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag app-yeahyeahyeah --label "runnumber=${GITHUB_RUN_ID}" --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }}
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/app-yeahyeahyeah
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag app-yeahyeahyeah $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Deploy container to digital ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /usr/src/app
            docker-compose stop app-yeahyeahyeah
            docker-compose up -d --no-deps --build --force-recreate app-yeahyeahyeah
