name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    name: Testing Commit Messages Convention
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.x
      - uses: actions/setup-node@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
