name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Testing Commits
        uses: actions/checkout@v3
        uses: wagoid/commitlint-github-action@v4
