name: System Health Check

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test:
    name: Reliability Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run health check
        run: npm run test:healthcheck

      - name: Create GitHub issue for health/smoke tests
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          labels: reliability
          title: Reliability tests failed
          body: |
            ### Your system not working properly. Please check your endpoints:

            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/feature/${{ github.base_ref }})

            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`

          assignees: webrooster, tomschall
