name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml

  tests:
    uses: ./.github/workflows/test.yml

  release-and-deploy:
    uses: ./.github/workflows/release.yml
    needs: [quality_checks, tests]
