name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  tests:
    uses: ./.github/workflows/test.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-and-deploy:
    uses: ./.github/workflows/release.yml
    needs: [quality_checks, tests]
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
      ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}

  healthchecks:
    uses: ./.github/workflows/healthcheck.yml
    needs: [release-and-deploy]
    if: ${{ needs.release-and-deploy.outputs.new_release_published == 'true' }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
