name: Jest tests

on:
  push:
    branches:
      - feature/jest
  workflow_dispatch:

jobs:
  test-with-jest:
    name: Run test cases with jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm run test
