name: Jest tests

on:
  push:
    branches:
      - feature/jest
  workflow_dispatch:

jobs:
  test-with-jest:
    name: Run test cases with jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run tests
        run: npm run test
